services:
  sda-hymnbook-mcp:
    build:
      context: .
    image: sda-hymnbook-mcp:latest
    container_name: sda-hymnbook-mcp
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    ports:
      - "62752:62752"
    networks:
      - default
      - sda-library-storage

networks:
  sda-library-storage:
    external: true
    name: sda-library-storage_default
